logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    ma.Anafal_Dahhaniback: DEBUG

spring:
  profiles:
    active: dev
  application:
    name: airbnb-back
  datasource:
    url: jdbc:postgresql://localhost:5432/Airbnb
    username: postgres
    password: Admin
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: Hikari
      auto-commit: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: airbnb_clone
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: airbnb_clone
    enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080

okta:
  oauth2:
    issuer: https://dev-pi70w68dmtszjxp6.us.auth0.com/
    client-id: DeISBlqxwJDr1C3b6dJf5Qu48O21yyaC
    client-secret: bIm8iGbNDTOBocZJR_pU960NDQ9aBWGo-FcVSJ4lTwZWpD8zZGXsuYVytNVJy80r

application:
  auth0:
    role-landlord-id: rol_qkXAdZGx7QrYtFeh
