logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    ma.Anafal_Dahhaniback: DEBUG

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/Airbnb
    username: postgres
    password: Admin
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariPool
      auto-commit: true
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        default_schema: airbnb_clone
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: airbnb_clone
    enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080

okta:
  oauth2:
    issuer: https://dev-pi70w68dmtszjxp6.us.auth0.com/
    client-id: DeISBlqxwJDr1C3b6dJf5Qu48O21yyaC
    client-secret: bIm8iGbNDTOBocZJR_pU960NDQ9aBWGo-FcVSJ4lTwZWpD8zZGXsuYVytNVJy80r

application:
  auth0:
    role-landlord-id: rol_qkXAdZGx7QrYtFeh
