logging:
  level:
    ROOT: info
    org.hibernate.SQL: INFO
    ma.Anafal_Dahhaniback: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Airbnb
    username: postgres
    password: Admin
  jpa:
    properties:
      hibernate:
        default_schema: airbnb_clone
#  liquibase:
#    contexts: prod
#    default-schema: airbnb_clone